obj-$(CONFIG_MACH_VIGOR) += board-vigor.o
obj-$(CONFIG_MACH_VIGOR) += board-vigor-gpiomux.o
obj-$(CONFIG_MACH_VIGOR) += board-vigor-keypad.o
obj-$(CONFIG_MACH_VIGOR) += board-vigor-mmc.o
obj-$(CONFIG_MACH_VIGOR) += board-vigor-storage.o
obj-$(CONFIG_MACH_VIGOR) += board-vigor-wifi.o
obj-$(CONFIG_MACH_VIGOR) += board-vigor-regulator.o
obj-$(CONFIG_MACH_VIGOR) += board-vigor-pmic.o
obj-$(CONFIG_MACH_VIGOR) += board-vigor-audio.o
obj-$(CONFIG_MACH_VIGOR) += board-vigor-rfkill.o
ifeq ($(CONFIG_MSM_CAMERA),y)
obj-$(CONFIG_MACH_VIGOR) += board-vigor-camera.o
endif
obj-$(CONFIG_MACH_VIGOR) += display/

